# Generated by Django 3.2.3 on 2021-05-19 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_Name', models.TextField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('location_type', models.TextField()),
                ('match_notes', models.TextField()),
                ('locality', models.CharField(max_length=30)),
                ('accuracy', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.CharField(max_length=30, null=True)),
                ('last_edit_notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('url', models.TextField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.CharField(max_length=30, null=True)),
                ('last_edit_notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sequences',
            fields=[
                ('id_pk', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cytB', models.TextField()),
                ('sequence2', models.TextField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.CharField(max_length=30, null=True)),
                ('last_edit_notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loc_Hap_Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.CharField(max_length=30, null=True)),
                ('last_edit_notes', models.TextField(null=True)),
                ('author_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_backend.publications')),
                ('haplotype_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_backend.sequences')),
                ('location_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_backend.locations')),
            ],
        ),
        migrations.CreateModel(
            name='LHPIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_bank_accession', models.CharField(max_length=30, null=True)),
                ('num_lions', models.IntegerField(null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.CharField(max_length=30, null=True)),
                ('last_edit_notes', models.TextField(null=True)),
                ('LHP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_backend.loc_hap_pub')),
            ],
        ),
    ]
