# Generated by Django 3.2.3 on 2021-05-25 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lhpindividual',
            old_name='modified_date',
            new_name='dateTimeModified',
        ),
        migrations.RenameField(
            model_name='lhpindividual',
            old_name='gen_bank_accession',
            new_name='genBankAccession',
        ),
        migrations.RenameField(
            model_name='lhpindividual',
            old_name='last_edit_notes',
            new_name='lastEditNotes',
        ),
        migrations.RenameField(
            model_name='lhpindividual',
            old_name='last_edited_by',
            new_name='lastEditedBy',
        ),
        migrations.RenameField(
            model_name='lhpindividual',
            old_name='num_lions',
            new_name='numLions',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='modified_date',
            new_name='dateTimeModified',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='last_edit_notes',
            new_name='lastEditNotes',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='last_edited_by',
            new_name='lastEditedBy',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='location_Name',
            new_name='locationName',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='location_type',
            new_name='locationType',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='match_notes',
            new_name='matchNotes',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='modified_date',
            new_name='dateTimeModified',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='last_edit_notes',
            new_name='lastEditNotes',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='last_edited_by',
            new_name='lastEditedBy',
        ),
        migrations.RenameField(
            model_name='sequences',
            old_name='modified_date',
            new_name='dateTimeModified',
        ),
        migrations.RenameField(
            model_name='sequences',
            old_name='last_edit_notes',
            new_name='lastEditNotes',
        ),
        migrations.RenameField(
            model_name='sequences',
            old_name='last_edited_by',
            new_name='lastEditedBy',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='sequences',
            name='sequence2',
        ),
        migrations.CreateModel(
            name='LocHapPub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeModified', models.DateTimeField(auto_now=True)),
                ('lastEditedBy', models.CharField(max_length=30, null=True)),
                ('lastEditNotes', models.TextField(null=True)),
                ('authorFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_backend.publications')),
                ('haplotypeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_backend.sequences')),
                ('locationFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_backend.locations')),
            ],
        ),
        migrations.AlterField(
            model_name='lhpindividual',
            name='LHP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_backend.lochappub'),
        ),
        migrations.DeleteModel(
            name='Loc_Hap_Pub',
        ),
    ]
