# Generated by Django 3.2.3 on 2021-05-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_backend', '0002_auto_20210525_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lochappub',
            old_name='authorFK',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='lochappub',
            old_name='haplotypeFK',
            new_name='haplotype',
        ),
        migrations.RenameField(
            model_name='lochappub',
            old_name='locationFK',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='sequences',
            old_name='id_pk',
            new_name='id',
        ),
    ]
