# Generated by Django 3.2.3 on 2021-05-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_backend', '0005_alter_lhpindividual_lasteditedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhpindividual',
            name='lastEditNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lhpindividual',
            name='numLions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='lastEditNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='lastEditedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lochappub',
            name='lastEditNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lochappub',
            name='lastEditedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='lastEditNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='lastEditedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='lastEditNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='lastEditedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
