# Generated by Django 4.0.4 on 2022-07-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_backend', '0006_auto_20210531_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhpindividual',
            name='numLions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
