#this file doesn't do anything, just testing code before putting it in the backend

databaseSeq = 'CAGAAACATTGGAATCATGTTGTTGCTCACAGTTATAGCTACAGCCTTCATAGGATATGTCTTACCGTAAAACCAAATATCCTTTTGAGGTGCAACTGTAATCACTAATCTCCTATCAGCAATCCCATACATCGGGGCCGACCTAGTAGAGTGGATCTGAGGAGGCTTCTCAGTAGACAAAGCCACCCTGACACGATTCTTTGCCTTCCACTTCATCCTTCCATTTATCATCTCAGCCCTAGCAGCAGTCCACCTCCTATTCCTCCATGAAACAGGATCTAATAACCCCTCAGGAATGGTATCTGACTCAGATAAAATTCCATTCCATCCATACTATACAATCAAAGATATCCTAGGCCTTCTAGTACTAACCTTAACACTCATACTACTCGTCCTATTCTCACCAGACCTATTAGGAGATCCCGACAACTATACCCCCGCCAATCCTCTAAGCACCCCTCCCCATATCAAACCAAAATGGTACTTCCTAAATGCATATGCAATCCTCCGATCTATTCCCAATAAACTAGGAGGAGTTCTAGCCCTAGTTCTATCCATCTTAATCTTAGCAATTATCCCTGCCCTCCACACTTCCAAACAGCGAGGAATAATGTAACGACCACTAAGTCAATGCTTATTCTGATTCCTAGTAGCGGACCTTCTGAAACTGACATGAATTGGTGGCCAGCCTGTAGAACACCCCTTCATCACCATCGGCCAACTAGCCTCCATCCTATACTTCTCCATTCTTCTCC'
querySeq = 'ATGAAACATTGGAATCATGTTGTTGCTCACAGTTATAGCTACAGCCTTCATAGGATATGTCTTACCGTGGGGCCAAATATCCTTTTGAGGTGCAACTGTAATCACTAATCTCCTATCAGCAATCCCATACATCGGGGCCGACCTAGTAGAGTGGATCTGAGGAGGCTTCTCAGTAGACAAAGCCACCCTGACACGATTCTTTGCCTTCCACTTCATCCTTCCATTTATCATCTCAGCCCTAGCAGCAGTCCACCTCCTATTCCTCCATGAAACAGGATCTAATAACCCCTCAGGAATGGTATCTGACTCAGATAAAATTCCATTCCATCCATACTATACAATCAAAGATATCCTAGGCCTTCTAGTACTAACCTTAACACTCATACTACTCGTCCTATTCTCACCAGACCTATTAGGAGATCCCGACAACTATACCCCCGCCAATCCTCTAAGCACCCCTCCCCATATCAAACCTGAATGGTACTTCCTATTTGCATATGCAATCCTCCGATCTATTCCCAATAAACTAGGAGGAGTTCTAGCCCTAGTTCTATCCATCTTAATCTTAGCAATTATCCCTGCCCTCCACACTTCCAAACAGCGAGGAATAATGTTTCGACCACTAAGTCAATGCTTATTCTGATTCCTAGTAGCGGACCTTCTGACCCTGACATGAATTGGTGGCCAGCCTGTAGAACACCCCTTCATCACCATCGGCCAACTAGCCTCCATCCTATACTTCTCCATTCTTCTAA'
mismatches = ['S','u','b','j','e','c','t',':',' ']
output = {}
sequenceDict = []
formattedSeqDict = []
for pos in range(0, len(databaseSeq)):
    if querySeq[pos] != databaseSeq[pos]:
        mismatches.append(databaseSeq[pos])
    else:
        mismatches.append('.')
query = 'Query:   ' + querySeq

def formattedOutput(sequence, mismatches, every=80):
    return ('\n'.join(sequence[i:i+every]+ '\n' + ''.join(mismatches[i:i+every]) for i in range(0, len(sequence), every)))

realoutput = formattedOutput(query, mismatches)
print (realoutput)



    

